### PR TITLE
fixes php8 notices in the new php8 branch

### PR DESCRIPTION
**Pull request by mattmary**
Add the thomas' patch in the devphp8 branch.

### CODE REVIEW

**Comment by lance-matomo** [comment]
Hey I don't have much experience with the developer documentation system yet. I've checked out this branch and the php8 branch on the developer documentation repository.
When I run generate.sh I get quite a few warnings and errors. I'm not sure if this is expected:
Could not open input file: ../app/composer.phar
Could not open input file: ../app/composer.phar
There was an error during the initialisation but we try to proceed anyway. FYI: error was 
The configuration file {/var/www/development/developer-documentation/piwik/config/config.ini.php} has not been found or could not be read.
 » Please check that /var/www/development/developer-documentation/piwik/config/config.ini.php is readable by the user 'lance'. 
 
PHP Warning:  Constant K_PATH_MAIN already defined in /var/www/development/developer-documentation/piwik/plugins/ScheduledReports/config/tcpdf_config.php on line 16
... lots more of these errors

Then a bunch of these ones:
Unresolved link: "DataTable" in Class Piwik\DataTable\Filter\AddColumnsProcessedMetrics

**Comment by mattmary** [comment]
Please install composer in your app project.

The config.ini.php error can be ignored.

Never had the constant error. which is you piwik branch?

You can ignore the Unresolved link errors.

**Comment by lance-matomo** [comment]
Thanks, looks like it is working. Should the travis.yml file be updated rather than deleted?

**Comment by mattmary** [comment]
Lance, It has been discussed with Thomas

**Review by lance-matomo — APPROVED** [review]

**Pull request merged**
